[package]
name = "genart"
version = "0.1.0"
edition = "2021"

[lints.clippy]
pedantic = "warn"

[dependencies]
anyhow = "1.0"
cairo-rs = { version = "0.19", features = ["png"] }
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
rand = "0.8"
